### ISSUE TITLE
Choosing the Right Tool

### ISSUE THREAD

**Issue by MatinMan** [MatinMan/JSClonesBugsAnalysis#3]
As a researcher, I want to perform tools and compare them in order to choose one of them 
Story Point: 5
Priority: 1
very-risky
Estimation: 20 h

**Comment by rigbypc** [comment]
Any progress on this? Please make a table with the headings: 
Tool name, strength, weakness

**Comment by ElnazTaqizadeh** [comment]
Based on the “Development nature matters: An empirical study of code clones in JavaScript applications”, among tools that can detect duplication of JavaScript code, MOSS, Simian, and PMD are widely studied in the literature.

**MOSS** is a general plagiarism detection tool for multiple languages that supports JavaScript. Researchers suggested that MOSS is very coarse-grained and is _not suitable_ for clone detection 

**Simian** and **PMD** are good at detecting identical clones but not renamed and gapped clones. These tools have low recall in detecting clones in Java and C. However, it is not known that whether their findings also apply to JavaScript because previous evaluations of these tools were conducted on other languages.

The authors of this paper have developed **JSCD** which is JavaScript clone detector. They have compared result of these tools together and come to the conclusion that for both Type-1 and Type-2 clones **JSCD** achieves better recall than Simian and PMD.

**Comment by ElnazTaqizadeh** [comment]
As a researcher, I want to compare tools for finding clones and choose the best one for JavaScript applications.

- [x] Raw Data: 2 survey on clone detection tools:
1. _A Survey on Software Clone Detection Research_
2. _Development nature matters: An empirical study of code clones in JavaScript applications_
- [x] Attributes: clone detection tools
- [x] Linking: clone detectors that can detect JavaScript code clones
- [x] Model: [finding right tool for clone detection.docx](https://github.com/MatinMan/JSClonesBugsAnalysis/files/116820/finding.right.tool.for.clone.detection.docx)
- [x] Reporting: most efficient detection tool for JavaScript clones
